#!/usr/bin/env zsh
# ┬┌─┌─┐┬ ┬┌┐ ┬┌┐┌┌┬┐┬┌┐┌┌─┐┌─┐
# ├┴┐├┤ └┬┘├┴┐││││ │││││││ ┬└─┐
# ┴ ┴└─┘ ┴ └─┘┴┘└┘─┴┘┴┘└┘└─┘└─┘
#--------------------------------------------
# (c) maarutan   https://github.com/maarutan

# ZVM - ZSH VI MODE
zvm_vi_yank () {
    zvm_yank
    printf %s "${CUTBUFFER}" | wl-copy -n # wayland
    # printf %s "${CUTBUFFER}" | xclip -selection clipboard # X11
    # printf %s "${CUTBUFFER}" | pbcopy # mac os
    zvm_exit_visual_mode
}

ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

bindkey "^W" backward-kill-word
bindkey "^?" backward-delete-char

bindkey '^N' history-beginning-search-forward # ctrl + n
bindkey '^P' history-beginning-search-backward # ctrl + p

# complete
bindkey "^I" fzf-tab-complete # tab
bindkey "^[[105;5u"  autosuggest-accept # ctrl + i

#fzf history
bindkey '^H' fzf_history_search # ctrl + h

# abbr
bindkey ' ' expand-abbr  # space
bindkey '^M' smart_enter # retrun | enter
bindkey '^ ' magic-space # ctrl + space

# sudo

bindkey '^R' add_sudo_to_start # ctrl + r
