#!/usr/bin/env bash

BUILD() {
    repo_dir=~/maaru-shell

    if [ -d "$repo_dir" ]; then
        bak_dir="${repo_dir}_bak_$(shuf -i 0-10000000 -n 1)"
        mv "$repo_dir" "$bak_dir"
        echo "Existing directory moved to: $bak_dir"
    fi

    if ! git clone https://github.com/maarutan/shell.git "$repo_dir"; then
        echo "Failed to clone the repository."
        exit 1
    fi

    if ! cd "$repo_dir/src"; then
        echo "Failed to change directory to src."
        exit 1
    fi

    if ! python ./buildpy; then
        echo "Build failed."
        exit 1
    fi
}

. /etc/os-release
case "$ID" in
    arch)
        if command -v zsh &>/dev/null; then
            echo "zsh already installed"
        else
            pacman -S --noconfirm zsh
        fi

        if command -v git &>/dev/null; then
            echo "git already installed"
        else
            pacman -S --noconfirm git
        fi

        if command -v python &>/dev/null; then
            echo "python already installed"
        else
            pacman -S --noconfirm python
        fi
        BUILD
        ;;
    *)
        if command -v zsh &>/dev/null; then
            echo "zsh already installed"
        else
            echo "zsh not found"
        fi

        if command -v git &>/dev/null; then
            echo "git already installed"
        else
            echo "git not found"
        fi

        if command -v python &>/dev/null; then
            echo "python already installed"
        else
            echo "python not found"
        fi
        BUILD
        ;;
esac

