#!/usr/bin/env bash

BUILD() {
    if [ -d ~/maaru-shell ]; then
        random_num=$((RANDOM * RANDOM))
        backup_file="~/maaru-shell-bak-$random_num.tar.gz"

        tar -czf $backup_file ~/maaru-shell
        echo "Backup created at $backup_file"
    fi

    git clone https://github.com/maarutan/shell.git ~/maaru-shell
    if [ $? -ne 0 ]; then
        echo "Failed to clone the repository."
        exit 1
    fi

    cd ~/maaru-shell/src || { echo "Failed to change directory"; exit 1; }
    python ./buildpy
    if [ $? -ne 0 ]; then
        echo "Build failed."
        exit 1
    fi
}

. /etc/os-release
case "$ID" in
    arch)
        if command -v zsh &>/dev/null; then
            echo "zsh already installed"
        else
            pacman -S --noconfirm zsh
        fi

        if command -v git &>/dev/null; then
            echo "git already installed"
        else
            pacman -S --noconfirm git
        fi

        if command -v python &>/dev/null; then
            echo "python already installed"
        else
            pacman -S --noconfirm python
        fi
        BUILD
        ;;
    *)
        if command -v zsh &>/dev/null; then
            echo "zsh already installed"
        else
            echo "zsh not found"
        fi

        if command -v git &>/dev/null; then
            echo "git already installed"
        else
            echo "git not found"
        fi

        if command -v python &>/dev/null; then
            echo "python already installed"
        else
            echo "python not found"
        fi
        BUILD
        ;;
esac

