#!/usr/bin/env bash

BUILD() {
    cd ~/maaru-shell/src || { echo "Failed to change directory"; exit 1; }
    python ./uninstallpy
    if [ $? -ne 0 ]; then
        echo "Build failed."
        exit 1
    fi
}

. /etc/os-release
case "$ID" in
    arch)
        if command -v zsh &>/dev/null; then
            echo "zsh already installed"
        else
            pacman -S --noconfirm zsh
        fi

        if command -v git &>/dev/null; then
            echo "git already installed"
        else
            pacman -S --noconfirm git
        fi

        if command -v python &>/dev/null; then
            echo "python already installed"
        else
            pacman -S --noconfirm python
        fi
        BUILD
        ;;
    *)
        if command -v zsh &>/dev/null; then
            echo "zsh already installed"
        else
            echo "zsh not found"
        fi

        if command -v git &>/dev/null; then
            echo "git already installed"
        else
            echo "git not found"
        fi

        if command -v python &>/dev/null; then
            echo "python already installed"
        else
            echo "python not found"
        fi
        BUILD
        ;;
esac


